"""delete key

Revision ID: 347a3de8f4f1
Revises: 4754fb87f894
Create Date: 2021-04-09 22:50:53.800952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347a3de8f4f1'
down_revision = '4754fb87f894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('key', sa.String(length=128), nullable=False))
    op.create_unique_constraint(op.f('uq_projects_key'), 'projects', ['key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_projects_key'), 'projects', type_='unique')
    op.drop_column('projects', 'key')
    # ### end Alembic commands ###
