"""Some changes

Revision ID: 4754fb87f894
Revises: 59dbb6202ece
Create Date: 2021-02-25 16:18:55.318227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4754fb87f894'
down_revision = '59dbb6202ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_groups_image_id_images', 'groups', type_='foreignkey')
    op.drop_column('groups', 'image_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('image_id', mysql.VARCHAR(length=128), nullable=True))
    op.create_foreign_key('fk_groups_image_id_images', 'groups', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
