"""add teamleads

Revision ID: 53ef39f7ed10
Revises: 7853d4428f07
Create Date: 2021-04-09 22:54:10.155479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ef39f7ed10'
down_revision = '7853d4428f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('teamlead_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_projects_teamlead_id_users'), 'projects', 'users', ['teamlead_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_teamlead_id_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'teamlead_id')
    # ### end Alembic commands ###
