"""Add fkeys

Revision ID: 59dbb6202ece
Revises: a0623b7ee393
Create Date: 2021-02-24 19:32:53.764916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59dbb6202ece'
down_revision = 'a0623b7ee393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('image_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(op.f('fk_directions_image_id_images'), 'directions', 'images', ['image_id'], ['id'])
    op.add_column('faculties', sa.Column('image_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(op.f('fk_faculties_image_id_images'), 'faculties', 'images', ['image_id'], ['id'])
    op.add_column('groups', sa.Column('image_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(op.f('fk_groups_image_id_images'), 'groups', 'images', ['image_id'], ['id'])
    op.add_column('laboratories', sa.Column('image_id', sa.String(length=128), nullable=True))
    op.create_foreign_key(op.f('fk_laboratories_image_id_images'), 'laboratories', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_laboratories_image_id_images'), 'laboratories', type_='foreignkey')
    op.drop_column('laboratories', 'image_id')
    op.drop_constraint(op.f('fk_groups_image_id_images'), 'groups', type_='foreignkey')
    op.drop_column('groups', 'image_id')
    op.drop_constraint(op.f('fk_faculties_image_id_images'), 'faculties', type_='foreignkey')
    op.drop_column('faculties', 'image_id')
    op.drop_constraint(op.f('fk_directions_image_id_images'), 'directions', type_='foreignkey')
    op.drop_column('directions', 'image_id')
    # ### end Alembic commands ###
