"""del multiple curators

Revision ID: 782cd6f5d156
Revises: e11bc596b70f
Create Date: 2021-05-07 09:43:41.127446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '782cd6f5d156'
down_revision = 'e11bc596b70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curators')
    op.add_column('projects', sa.Column('curator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_projects_curator_id_users'), 'projects', 'users', ['curator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_curator_id_users'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'curator_id')
    op.create_table('curators',
    sa.Column('curator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['users.id'], name='fk_curators_curator_id_users'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_curators_project_id_projects'),
    sa.PrimaryKeyConstraint('curator_id', 'project_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
