"""delete key2

Revision ID: 7853d4428f07
Revises: 347a3de8f4f1
Create Date: 2021-04-09 22:51:46.250259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7853d4428f07'
down_revision = '347a3de8f4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_projects_key', table_name='projects')
    op.drop_column('projects', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('key', mysql.VARCHAR(length=128), nullable=False))
    op.create_index('uq_projects_key', 'projects', ['key'], unique=True)
    # ### end Alembic commands ###
