"""del object_type

Revision ID: 964890fedda1
Revises: 53ef39f7ed10
Create Date: 2021-04-10 18:09:59.384318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '964890fedda1'
down_revision = '53ef39f7ed10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'object_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('object_type', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
