"""add type_id

Revision ID: c80e784c7dbe
Revises: 964890fedda1
Create Date: 2021-04-10 18:29:50.162485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80e784c7dbe'
down_revision = '964890fedda1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_images_type_id_types'), 'images', 'types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_images_type_id_types'), 'images', type_='foreignkey')
    op.drop_column('images', 'type_id')
    # ### end Alembic commands ###
